language: go

go:
  - 1.7
  - 1.8
  - 1.9
  - master

install:
  - export GLIDE_VERSION="0.13.1"
  - wget "https://github.com/Masterminds/glide/releases/download/$GLIDE_VERSION/glide-$GLIDE_VERSION-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-$GLIDE_VERSION-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"
  - glide install

script: go test ./... -cover -v
